# pubspec.yaml
name: app_movil
description: "App que utiliza las herramientas del teléfono."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Asegúrate de que coincida con tu versión de Dart SDK

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.0.20
  geolocator: ^9.0.2
  mobile_scanner: ^5.2.3
  sensors_plus: ^6.1.0
  fl_chart: ^0.55.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Actualiza a la versión compatible más reciente

flutter:
  uses-material-design: true
  generate: true  # Asegúrate de incluir esta línea

  assets:
    - assets/images/
    - assets/logo.png
    - assets/images/send.png
    - .env
